### ISSUE TITLE
Thank you. 

### ISSUE THREAD

**Issue by evereklili** [MicrosoftDocs/xamarin-docs.tr-tr#5]
Thank you. I want to Oracle Document  similary. But This systems(documents) 

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: dac28e18-875a-cb51-a031-717692255d0a
* Version Independent ID: f2e625c7-18a7-c090-fa92-9d635ac39164
* Content: [Xamarin.Android için Android SDK'sını ayarlama - Xamarin](https://docs.microsoft.com/tr-tr/xamarin/android/get-started/installation/android-sdk?ide=vs&tabs=windows)
* Content Source: [docs/android/get-started/installation/android-sdk.md](https://github.com/MicrosoftDocs/xamarin-docs.tr-TR/blob/live/docs/android/get-started/installation/android-sdk.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by CeciAc** [comment]
Hello, @evereklili 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/xamarin-docs/issues/1291.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
